services:
  - type: web
    name: ai-bridge
    env: python
    plan: free # optional
    buildCommand: "pip install -r requirements.txt && flask db upgrade"
    startCommand: "gunicorn --workers 4 --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: OPENAI_API_KEY
        sync: false # Do not sync from .env file, use Render's secret management
      - key: TARGET_API_KEY
        sync: false
      - key: TARGET_API_BASE_URL
        sync: false 