services:
  - type: web
    name: ai-bridge
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN
        generateValue: true
      - key: BEARER_TOKEN
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: TARGET_API_KEY
        sync: false
      - key: TARGET_API_BASE_URL
        sync: false 